[package]
name = "file_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
itertools = "0.10.5"
futures = "0.3"
flate2 = "1.0"
chrono = "0.4.23"
serde_json = "1.0"
